In [56]:
  from sklearn.feature_extraction.text import TfidfVectorizer
  from sklearn.metrics.pairwise import cosine_similarity
  import pandas as pd
  import numpy as np

In [57]:
sentences = [
            "I feel stress at job every day",
            "My job pressure is very high due to stress",
              "I havve  stress and anxiety",
        "Mental stress affects health",
    "Work life balance is important",
    "Exercise reduces anxiety and stress"
]

In [ ]:
# Ask the user to enter a query
query = input("Enter your query: ")
# Convert the query into a list
query = [query]
print("\nYour query:", query)

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

all_text = sentences + query
tfidf = vectorizer.fit_transform(all_text)
vocab = vectorizer.get_feature_names_out()
print("Vocabulary:\n", vocab)
for i, sentence in enumerate(sentences):
    print(f"\nSentence {i+1}: {sentence}")
    print("Words used:", sentence.lower().split())

Vocabulary:
 ['amounts' 'analyze' 'and' 'artificial' 'basketball' 'books' 'data'
 'enjoy' 'for' 'friends' 'helps' 'improve' 'intelligence' 'is' 'knowledge'
 'large' 'learning' 'like' 'machine' 'my' 'of' 'playing' 'programming'
 'python' 'reading' 'science' 'useful' 'uses' 'with']

Sentence 1: I enjoy learning Python programming
Words used: ['i', 'enjoy', 'learning', 'python', 'programming']

Sentence 2: Python programming is useful for data science
Words used: ['python', 'programming', 'is', 'useful', 'for', 'data', 'science']

Sentence 3: Machine learning helps analyze large amounts of data
Words used: ['machine', 'learning', 'helps', 'analyze', 'large', 'amounts', 'of', 'data']

Sentence 4: I like playing basketball with my friends
Words used: ['i', 'like', 'playing', 'basketball', 'with', 'my', 'friends']

Sentence 5: Data science uses Python and machine learning
Words used: ['data', 'science', 'uses', 'python', 'and', 'machine', 'learning']

Sentence 6: Reading books helps improve knowledge
Words used: ['reading', 'books', 'helps', 'improve', 'knowledge']

In [49]:
tfidf_matrix = vectorizer.fit_transform(sentences + query)

sentence_vectors = tfidf_matrix[:-1]
query_vector = tfidf_matrix[-1]

tfidf_df = pd.DataFrame(
    sentence_vectors.toarray(),
    columns=vocab,
    index=sentences
)

sentence_bow = []

for sentence in sentences:
    row = tfidf_df.loc[sentence]
    bow = row[row > 0]

    sentence_bow.append({
        "Sentence": sentence,
        "Bag_of_TFIDF_Vectors": bow.to_dict()
    })


query_row = pd.Series(
    query_vector.toarray()[0],
    index=vocab
)

query_bow = query_row[query_row > 0]

sentence_bow.append({

    "Bag_of_TFIDF_Vectors": query_bow.to_dict()
})

final_df = pd.DataFrame(sentence_bow)

final_df.style.set_properties(
    **{
        'text-align': 'left',
        'font-family': 'monospace',
        'white-space': 'pre',
    }
)

In [50]:
import numpy as np

query_array = query_vector.toarray()[0]

for i in range(len(sentences)):
    sentence_array = sentence_vectors[i].toarray()[0]
    dot = np.dot(query_array, sentence_array)
    print(f"Dot product with sentence {i+1}: {dot}")

Dot product with sentence 1: 0.0
Dot product with sentence 2: 0.0
Dot product with sentence 3: 0.0
Dot product with sentence 4: 0.0
Dot product with sentence 5: 0.0
Dot product with sentence 6: 0.0

In [51]:
query_mag = np.sqrt(np.sum(query_array ** 2))
print("Query magnitude:", query_mag)

for i in range(len(sentences)):
    sentence_array = sentence_vectors[i].toarray()[0]
    sent_mag = np.sqrt(np.sum(sentence_array ** 2))
    print(f"Magnitude of sentence {i+1}:", sent_mag)

Query magnitude: 1.0
Magnitude of sentence 1: 1.0
Magnitude of sentence 2: 1.0
Magnitude of sentence 3: 0.9999999999999999
Magnitude of sentence 4: 0.9999999999999999
Magnitude of sentence 5: 1.0
Magnitude of sentence 6: 1.0

In [52]:
results = []
for i in range(len(sentences)):
    sentence_array = sentence_vectors[i].toarray()[0]

    dot = np.dot(query_array, sentence_array)
    sent_mag = np.sqrt(np.sum(sentence_array ** 2))

    cosine_sim = dot / (query_mag * sent_mag)

    print(f"\nSentence: {sentences[i]}")
    print("Cosine Similarity:", cosine_sim)

    results.append({
        "Sentence": sentences[i],
        "Cosine Similarity": cosine_sim
    })

    print(f"\nSentence {i+1}: {sentences[i]}")
    print("Cosine Similarity:", cosine_sim)

Sentence: I enjoy learning Python programming
Cosine Similarity: 0.0

Sentence 1: I enjoy learning Python programming
Cosine Similarity: 0.0

Sentence: Python programming is useful for data science
Cosine Similarity: 0.0

Sentence 2: Python programming is useful for data science
Cosine Similarity: 0.0

Sentence: Machine learning helps analyze large amounts of data
Cosine Similarity: 0.0

Sentence 3: Machine learning helps analyze large amounts of data
Cosine Similarity: 0.0

Sentence: I like playing basketball with my friends
Cosine Similarity: 0.0

Sentence 4: I like playing basketball with my friends
Cosine Similarity: 0.0

Sentence: Data science uses Python and machine learning
Cosine Similarity: 0.0

Sentence 5: Data science uses Python and machine learning
Cosine Similarity: 0.0

Sentence: Reading books helps improve knowledge
Cosine Similarity: 0.0

Sentence 6: Reading books helps improve knowledge
Cosine Similarity: 0.0

In [53]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Cosine Similarity",
    ascending=False
)

results_df = results_df.reset_index(drop=True)

print("\nSimilarity Results:")
display(results_df)

Similarity Results:

                                            Sentence  Cosine Similarity
0                I enjoy learning Python programming                0.0
1      Python programming is useful for data science                0.0
2  Machine learning helps analyze large amounts o...                0.0
3          I like playing basketball with my friends                0.0
4      Data science uses Python and machine learning                0.0
5              Reading books helps improve knowledge                0.0