In [1]:
  from sklearn.feature_extraction.text import TfidfVectorizer
  from sklearn.metrics.pairwise import cosine_similarity
  import pandas as pd
  import numpy as np

In [2]:
# Create a large text document

document = """
Paragraph 1:
Workplace stress can affect employees in many different ways. Long working hours,
heavy workloads, strict deadlines, and pressure from managers can make people feel
tired and overwhelmed. When stress continues for a long period, employees may have
difficulty concentrating and may become less productive.

Paragraph 2:
Maintaining a healthy work life balance is important for physical and mental well-being.
Employees need enough time for work, family, friends, exercise, hobbies, and rest.
When work takes up nearly all of a person's time, stress and dissatisfaction can increase.

Paragraph 3:
Exercise is one way people can improve their physical health and manage everyday stress.
Walking, running, swimming, cycling, and strength training can help people stay active.
Regular physical activity may also improve sleep and mood.

Paragraph 4:
Good sleep is an important part of a healthy lifestyle. Adults need consistent quality
sleep to support concentration, memory, mood, and physical health. Staying up late to
finish work can make people tired the next day.

Paragraph 5:
Healthy eating provides the body with nutrients and energy needed for daily activities.
A balanced diet can include vegetables, fruits, whole grains, protein sources, and
healthy fats. Drinking enough water is also important.

Paragraph 6:
Time management can help students and employees complete their responsibilities
without unnecessary pressure. A person can make a list of important tasks, organize
them by priority, and divide large projects into smaller steps.

Paragraph 7:
Learning new skills requires practice, patience, and repetition. Beginners often make
mistakes when they first learn programming, mathematics, writing, or another subject.
Mistakes can provide useful information about what needs more practice.

Paragraph 8:
Python is a popular programming language used for data analysis, automation, web
development, and machine learning. Beginners often start by learning variables,
strings, numbers, lists, dictionaries, conditions, and loops.

Paragraph 9:
Data analysis involves collecting, cleaning, exploring, and interpreting information.
A data analyst may begin by loading a dataset and checking its rows, columns, data
types, and missing values. After cleaning the data, the analyst can calculate statistics.

Paragraph 10:
Machine learning allows computers to learn patterns from data and use those patterns
to make predictions or classifications. Supervised learning uses labeled data, while
unsupervised learning works with data without predefined labels.

Paragraph 11:
Customer segmentation is a business technique used to divide customers into groups
based on shared characteristics or behaviors. Companies may examine purchase
frequency, spending amount, and how recently a customer purchased something.

Paragraph 12:
Online shopping has changed the way customers discover and purchase products.
E-commerce businesses collect information about orders, products, prices, customers,
and transaction dates. Analyzing this information can help businesses understand
purchasing patterns.

Paragraph 13:
Artificial intelligence is increasingly used in business applications. Organizations may
use AI to analyze documents, answer customer questions, detect patterns, recommend
products, and automate repetitive tasks.

Paragraph 14:
Natural language processing allows computers to work with human language. Common
NLP tasks include tokenization, stopword removal, stemming, lemmatization, part of
speech tagging, sentiment analysis, and text classification.

Paragraph 15:
Text similarity is useful when a system needs to determine how closely two pieces of
text are related. Search engines, document retrieval systems, recommendation systems,
and duplicate detection tools can use similarity methods.

Paragraph 16:
TF-IDF stands for term frequency inverse document frequency. Term frequency measures
how often a word appears in a document, while inverse document frequency reduces the
importance of words that appear in many documents.

Paragraph 17:
Cosine similarity measures the angle between two numerical vectors. A value close to
one generally indicates that the vectors point in similar directions, while a value close
to zero indicates little similarity.

Paragraph 18:
Search systems often compare a user's query with a collection of documents. The query
can be converted into the same numerical representation as the documents. A similarity
score can then be calculated for every document.

Paragraph 19:
A recommendation system can use similarities between items to suggest content to users.
For example, a system might compare descriptions of books, movies, products, or
articles. Similar descriptions may have higher similarity scores.

Paragraph 20:
Data visualization helps people understand information through charts and graphs.
Bar charts can compare categories, line charts can show changes over time, histograms
can display distributions, and scatter plots can show relationships between variables.

Paragraph 21:
A database stores organized information so that it can be searched, updated, and
managed efficiently. Relational databases commonly organize information into tables
containing rows and columns. SQL can be used to select, filter, group, and sort data.

Paragraph 22:
Cybersecurity focuses on protecting computers, networks, applications, and information
from unauthorized access or damage. Strong passwords, multi-factor authentication,
software updates, and backups can reduce security risks.

Paragraph 23:
Cloud computing provides access to computing resources such as storage, databases,
servers, and applications through internet-connected services. Businesses can use cloud
platforms to store data and run applications.

Paragraph 24:
Project management involves planning work, assigning responsibilities, tracking progress,
and managing deadlines. A project may be divided into smaller tasks so that progress
can be measured.

Paragraph 25:
Communication is an important skill in education and the workplace. Clear communication
helps people understand expectations, explain ideas, and solve problems. Asking
questions and listening carefully can reduce misunderstandings.

Paragraph 26:
Financial planning helps people understand their income, expenses, savings, and financial
goals. Creating a budget can show where money is being spent each month. People may
set aside money for emergencies, education, housing, or retirement.

Paragraph 27:
Investing involves putting money into assets with the expectation that they may generate
returns over time. Stocks, bonds, mutual funds, and other investments have different
characteristics and levels of risk.

Paragraph 28:
Weather describes atmospheric conditions such as temperature, precipitation, wind,
humidity, and cloud cover. Weather can change from day to day and sometimes from
hour to hour.

Paragraph 29:
Climate change refers to long-term changes in temperatures and weather patterns.
Scientists study temperature records, ocean measurements, ice observations, and other
evidence to understand climate trends.

Paragraph 30:
Travel planning involves choosing destinations, transportation, accommodation, activities,
and a budget. Travelers may research weather, local transportation, cultural attractions,
and seasonal conditions before a trip.

Paragraph 31:
Reading is an effective way to develop knowledge and language skills. Regular reading
exposes people to new vocabulary, ideas, writing styles, and information. Students can
improve comprehension by identifying the main idea and supporting details.

Paragraph 32:
Writing requires organizing ideas so that readers can follow the information easily.
A strong paragraph usually has a clear main idea followed by supporting information.
Revising a draft can improve grammar, structure, word choice, and clarity.

Paragraph 33:
A large document may contain hundreds or thousands of paragraphs covering different
topics. Finding relevant information manually can take a long time. Text similarity
methods can help a program identify paragraphs that are related to a search query.

Paragraph 34:
Employees may experience pressure when they have too many tasks and not enough
time to complete them. Planning work carefully and communicating with managers can
help teams understand priorities and deadlines.

Paragraph 35:
Students can improve their programming skills by practicing small Python programs.
Working with variables, loops, conditions, functions, lists, and dictionaries creates a
foundation for more advanced data science and machine learning.

Paragraph 36:
A data scientist may use pandas to manipulate datasets, NumPy for numerical operations,
and Matplotlib to create charts. These tools are commonly used together during
exploratory data analysis.

Paragraph 37:
Machine learning models should be evaluated using appropriate metrics. Classification
models may use accuracy, precision, recall, and F1 score, while regression models can
use metrics such as mean squared error and R squared.

Paragraph 38:
Natural language processing can be used to analyze customer reviews, news articles,
emails, social media posts, and other text. Text preprocessing often prepares raw text
before it is given to a machine learning algorithm.

Paragraph 39:
Document similarity can help users find related information in large collections of
documents. Instead of reading every document manually, a program can calculate
similarity scores and return the most relevant results.

Paragraph 40:
The purpose of a text search system is to help users quickly find information that
matches their question. TF-IDF and cosine similarity provide a simple way to build
such a system and understand the basic idea behind information retrieval.
"""

# Save the document

with open("large_document.txt", "w", encoding="utf-8") as file:
    file.write(document)

print("large_document.txt created successfully!")
# Split the document into paragraphs

sentences = document.split("\n\n")

# Remove empty paragraphs

sentences = [
    sentence.strip()
    for sentence in sentences
    if sentence.strip()
]

print("Number of paragraphs:", len(sentences))

large_document.txt created successfully!
Number of paragraphs: 40

In [3]:
# Ask the user to enter a query
query = input("Enter your query: ")
# Convert the query into a list
query = [query]
print("\nYour query:", query)

Enter your query: Working with variables

Your query: ['Working with variables']

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

all_text = sentences + query
tfidf = vectorizer.fit_transform(all_text)
vocab = vectorizer.get_feature_names_out()
print("Vocabulary:\n", vocab)
for i, sentence in enumerate(sentences):
    print(f"\nSentence {i+1}: {sentence}")
    print("Words used:", sentence.lower().split())

Vocabulary:
 ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20' '21' '22' '23'
 '24' '25' '26' '27' '28' '29' '30' '31' '32' '33' '34' '35' '36' '37'
 '38' '39' '40' 'about' 'access' 'accommodation' 'accuracy' 'active'
 'activities' 'activity' 'adults' 'advanced' 'affect' 'after' 'ai'
 'algorithm' 'all' 'allows' 'also' 'amount' 'an' 'analysis' 'analyst'
 'analyze' 'analyzing' 'and' 'angle' 'another' 'answer' 'appear' 'appears'
 'applications' 'appropriate' 'are' 'articles' 'artificial' 'as' 'aside'
 'asking' 'assets' 'assigning' 'atmospheric' 'attractions'
 'authentication' 'automate' 'automation' 'backups' 'balance' 'balanced'
 'bar' 'based' 'basic' 'be' 'become' 'before' 'begin' 'beginners'
 'behaviors' 'behind' 'being' 'between' 'body' 'bonds' 'books' 'budget'
 'build' 'business' 'businesses' 'by' 'calculate' 'calculated' 'can'
 'carefully' 'categories' 'change' 'changed' 'changes' 'characteristics'
 'charts' 'checking' 'choice' 'choosing' 'clarity' 'classification'
 'classifications' 'cleaning' 'clear' 'climate' 'close' 'closely' 'cloud'
 'collect' 'collecting' 'collection' 'collections' 'columns' 'commerce'
 'common' 'commonly' 'communicating' 'communication' 'companies' 'compare'
 'complete' 'comprehension' 'computers' 'computing' 'concentrating'
 'concentration' 'conditions' 'connected' 'consistent' 'contain'
 'containing' 'content' 'continues' 'converted' 'cosine' 'cover'
 'covering' 'create' 'creates' 'creating' 'cultural' 'customer'
 'customers' 'cybersecurity' 'cycling' 'daily' 'damage' 'data' 'database'
 'databases' 'dataset' 'datasets' 'dates' 'day' 'deadlines' 'describes'
 'descriptions' 'destinations' 'details' 'detect' 'detection' 'determine'
 'develop' 'development' 'dictionaries' 'diet' 'different' 'difficulty'
 'directions' 'discover' 'display' 'dissatisfaction' 'distributions'
 'divide' 'divided' 'document' 'documents' 'draft' 'drinking' 'duplicate'
 'during' 'each' 'easily' 'eating' 'education' 'effective' 'efficiently'
 'emails' 'emergencies' 'employees' 'energy' 'engines' 'enough' 'error'
 'evaluated' 'every' 'everyday' 'evidence' 'examine' 'example' 'exercise'
 'expectation' 'expectations' 'expenses' 'experience' 'explain'
 'exploratory' 'exploring' 'exposes' 'f1' 'factor' 'family' 'fats' 'feel'
 'filter' 'financial' 'find' 'finding' 'finish' 'first' 'focuses' 'follow'
 'followed' 'for' 'foundation' 'frequency' 'friends' 'from' 'fruits'
 'functions' 'funds' 'generally' 'generate' 'given' 'goals' 'good'
 'grains' 'grammar' 'graphs' 'group' 'groups' 'has' 'have' 'health'
 'healthy' 'heavy' 'help' 'helps' 'higher' 'histograms' 'hobbies' 'hour'
 'hours' 'housing' 'how' 'human' 'humidity' 'hundreds' 'ice' 'idea'
 'ideas' 'identify' 'identifying' 'idf' 'importance' 'important' 'improve'
 'in' 'include' 'income' 'increase' 'increasingly' 'indicates'
 'information' 'instead' 'intelligence' 'internet' 'interpreting' 'into'
 'inverse' 'investing' 'investments' 'involves' 'is' 'it' 'items' 'its'
 'knowledge' 'labeled' 'labels' 'language' 'large' 'late' 'learn'
 'learning' 'lemmatization' 'less' 'levels' 'life' 'lifestyle' 'line'
 'list' 'listening' 'lists' 'little' 'loading' 'local' 'long' 'loops'
 'machine' 'main' 'maintaining' 'make' 'manage' 'managed' 'management'
 'managers' 'managing' 'manipulate' 'manually' 'many' 'matches'
 'mathematics' 'matplotlib' 'may' 'mean' 'measured' 'measurements'
 'measures' 'media' 'memory' 'mental' 'methods' 'metrics' 'might'
 'missing' 'mistakes' 'misunderstandings' 'models' 'money' 'month' 'mood'
 'more' 'most' 'movies' 'multi' 'mutual' 'natural' 'nearly' 'need'
 'needed' 'needs' 'networks' 'new' 'news' 'next' 'nlp' 'not' 'numbers'
 'numerical' 'numpy' 'nutrients' 'observations' 'ocean' 'of' 'often' 'on'
 'one' 'online' 'operations' 'or' 'orders' 'organizations' 'organize'
 'organized' 'organizing' 'other' 'over' 'overwhelmed' 'pandas'
 'paragraph' 'paragraphs' 'part' 'passwords' 'patience' 'patterns'
 'people' 'period' 'person' 'physical' 'pieces' 'planning' 'platforms'
 'plots' 'point' 'popular' 'posts' 'practice' 'practicing' 'precipitation'
 'precision' 'predefined' 'predictions' 'prepares' 'preprocessing'
 'pressure' 'prices' 'priorities' 'priority' 'problems' 'processing'
 'productive' 'products' 'program' 'programming' 'programs' 'progress'
 'project' 'projects' 'protecting' 'protein' 'provide' 'provides'
 'purchase' 'purchased' 'purchasing' 'purpose' 'putting' 'python'
 'quality' 'query' 'question' 'questions' 'quickly' 'raw' 'readers'
 'reading' 'recall' 'recently' 'recommend' 'recommendation' 'records'
 'reduce' 'reduces' 'refers' 'regression' 'regular' 'related' 'relational'
 'relationships' 'relevant' 'removal' 'repetition' 'repetitive'
 'representation' 'requires' 'research' 'resources' 'responsibilities'
 'rest' 'results' 'retirement' 'retrieval' 'return' 'returns' 'reviews'
 'revising' 'risk' 'risks' 'rows' 'run' 'running' 'same' 'savings'
 'scatter' 'science' 'scientist' 'scientists' 'score' 'scores' 'search'
 'searched' 'seasonal' 'security' 'segmentation' 'select' 'sentiment'
 'servers' 'services' 'set' 'shared' 'shopping' 'should' 'show' 'similar'
 'similarities' 'similarity' 'simple' 'skill' 'skills' 'sleep' 'small'
 'smaller' 'so' 'social' 'software' 'solve' 'something' 'sometimes' 'sort'
 'sources' 'speech' 'spending' 'spent' 'sql' 'squared' 'stands' 'start'
 'statistics' 'stay' 'staying' 'stemming' 'steps' 'stocks' 'stopword'
 'storage' 'store' 'stores' 'strength' 'stress' 'strict' 'strings'
 'strong' 'structure' 'students' 'study' 'styles' 'subject' 'such'
 'suggest' 'supervised' 'support' 'supporting' 'swimming' 'system'
 'systems' 'tables' 'tagging' 'take' 'takes' 'tasks' 'teams' 'technique'
 'temperature' 'temperatures' 'term' 'text' 'tf' 'that' 'the' 'their'
 'them' 'then' 'these' 'they' 'this' 'those' 'thousands' 'through' 'time'
 'tired' 'to' 'together' 'tokenization' 'too' 'tools' 'topics' 'tracking'
 'training' 'transaction' 'transportation' 'travel' 'travelers' 'trends'
 'trip' 'two' 'types' 'unauthorized' 'understand' 'unnecessary'
 'unsupervised' 'up' 'updated' 'updates' 'use' 'used' 'useful' 'user'
 'users' 'uses' 'using' 'usually' 'value' 'values' 'variables' 'vectors'
 'vegetables' 'visualization' 'vocabulary' 'walking' 'water' 'way' 'ways'
 'weather' 'web' 'well' 'what' 'when' 'where' 'while' 'whole' 'wind'
 'with' 'without' 'word' 'words' 'work' 'working' 'workloads' 'workplace'
 'works' 'writing' 'zero']

Sentence 1: Paragraph 1:
Workplace stress can affect employees in many different ways. Long working hours,
heavy workloads, strict deadlines, and pressure from managers can make people feel
tired and overwhelmed. When stress continues for a long period, employees may have
difficulty concentrating and may become less productive.
Words used: ['paragraph', '1:', 'workplace', 'stress', 'can', 'affect', 'employees', 'in', 'many', 'different', 'ways.', 'long', 'working', 'hours,', 'heavy', 'workloads,', 'strict', 'deadlines,', 'and', 'pressure', 'from', 'managers', 'can', 'make', 'people', 'feel', 'tired', 'and', 'overwhelmed.', 'when', 'stress', 'continues', 'for', 'a', 'long', 'period,', 'employees', 'may', 'have', 'difficulty', 'concentrating', 'and', 'may', 'become', 'less', 'productive.']

Sentence 2: Paragraph 2:
Maintaining a healthy work life balance is important for physical and mental well-being.
Employees need enough time for work, family, friends, exercise, hobbies, and rest.
When work takes up nearly all of a person's time, stress and dissatisfaction can increase.
Words used: ['paragraph', '2:', 'maintaining', 'a', 'healthy', 'work', 'life', 'balance', 'is', 'important', 'for', 'physical', 'and', 'mental', 'well-being.', 'employees', 'need', 'enough', 'time', 'for', 'work,', 'family,', 'friends,', 'exercise,', 'hobbies,', 'and', 'rest.', 'when', 'work', 'takes', 'up', 'nearly', 'all', 'of', 'a', "person's", 'time,', 'stress', 'and', 'dissatisfaction', 'can', 'increase.']

Sentence 3: Paragraph 3:
Exercise is one way people can improve their physical health and manage everyday stress.
Walking, running, swimming, cycling, and strength training can help people stay active.
Regular physical activity may also improve sleep and mood.
Words used: ['paragraph', '3:', 'exercise', 'is', 'one', 'way', 'people', 'can', 'improve', 'their', 'physical', 'health', 'and', 'manage', 'everyday', 'stress.', 'walking,', 'running,', 'swimming,', 'cycling,', 'and', 'strength', 'training', 'can', 'help', 'people', 'stay', 'active.', 'regular', 'physical', 'activity', 'may', 'also', 'improve', 'sleep', 'and', 'mood.']

Sentence 4: Paragraph 4:
Good sleep is an important part of a healthy lifestyle. Adults need consistent quality
sleep to support concentration, memory, mood, and physical health. Staying up late to
finish work can make people tired the next day.
Words used: ['paragraph', '4:', 'good', 'sleep', 'is', 'an', 'important', 'part', 'of', 'a', 'healthy', 'lifestyle.', 'adults', 'need', 'consistent', 'quality', 'sleep', 'to', 'support', 'concentration,', 'memory,', 'mood,', 'and', 'physical', 'health.', 'staying', 'up', 'late', 'to', 'finish', 'work', 'can', 'make', 'people', 'tired', 'the', 'next', 'day.']

Sentence 5: Paragraph 5:
Healthy eating provides the body with nutrients and energy needed for daily activities.
A balanced diet can include vegetables, fruits, whole grains, protein sources, and
healthy fats. Drinking enough water is also important.
Words used: ['paragraph', '5:', 'healthy', 'eating', 'provides', 'the', 'body', 'with', 'nutrients', 'and', 'energy', 'needed', 'for', 'daily', 'activities.', 'a', 'balanced', 'diet', 'can', 'include', 'vegetables,', 'fruits,', 'whole', 'grains,', 'protein', 'sources,', 'and', 'healthy', 'fats.', 'drinking', 'enough', 'water', 'is', 'also', 'important.']

Sentence 6: Paragraph 6:
Time management can help students and employees complete their responsibilities
without unnecessary pressure. A person can make a list of important tasks, organize
them by priority, and divide large projects into smaller steps.
Words used: ['paragraph', '6:', 'time', 'management', 'can', 'help', 'students', 'and', 'employees', 'complete', 'their', 'responsibilities', 'without', 'unnecessary', 'pressure.', 'a', 'person', 'can', 'make', 'a', 'list', 'of', 'important', 'tasks,', 'organize', 'them', 'by', 'priority,', 'and', 'divide', 'large', 'projects', 'into', 'smaller', 'steps.']

Sentence 7: Paragraph 7:
Learning new skills requires practice, patience, and repetition. Beginners often make
mistakes when they first learn programming, mathematics, writing, or another subject.
Mistakes can provide useful information about what needs more practice.
Words used: ['paragraph', '7:', 'learning', 'new', 'skills', 'requires', 'practice,', 'patience,', 'and', 'repetition.', 'beginners', 'often', 'make', 'mistakes', 'when', 'they', 'first', 'learn', 'programming,', 'mathematics,', 'writing,', 'or', 'another', 'subject.', 'mistakes', 'can', 'provide', 'useful', 'information', 'about', 'what', 'needs', 'more', 'practice.']

Sentence 8: Paragraph 8:
Python is a popular programming language used for data analysis, automation, web
development, and machine learning. Beginners often start by learning variables,
strings, numbers, lists, dictionaries, conditions, and loops.
Words used: ['paragraph', '8:', 'python', 'is', 'a', 'popular', 'programming', 'language', 'used', 'for', 'data', 'analysis,', 'automation,', 'web', 'development,', 'and', 'machine', 'learning.', 'beginners', 'often', 'start', 'by', 'learning', 'variables,', 'strings,', 'numbers,', 'lists,', 'dictionaries,', 'conditions,', 'and', 'loops.']

Sentence 9: Paragraph 9:
Data analysis involves collecting, cleaning, exploring, and interpreting information.
A data analyst may begin by loading a dataset and checking its rows, columns, data
types, and missing values. After cleaning the data, the analyst can calculate statistics.
Words used: ['paragraph', '9:', 'data', 'analysis', 'involves', 'collecting,', 'cleaning,', 'exploring,', 'and', 'interpreting', 'information.', 'a', 'data', 'analyst', 'may', 'begin', 'by', 'loading', 'a', 'dataset', 'and', 'checking', 'its', 'rows,', 'columns,', 'data', 'types,', 'and', 'missing', 'values.', 'after', 'cleaning', 'the', 'data,', 'the', 'analyst', 'can', 'calculate', 'statistics.']

Sentence 10: Paragraph 10:
Machine learning allows computers to learn patterns from data and use those patterns
to make predictions or classifications. Supervised learning uses labeled data, while
unsupervised learning works with data without predefined labels.
Words used: ['paragraph', '10:', 'machine', 'learning', 'allows', 'computers', 'to', 'learn', 'patterns', 'from', 'data', 'and', 'use', 'those', 'patterns', 'to', 'make', 'predictions', 'or', 'classifications.', 'supervised', 'learning', 'uses', 'labeled', 'data,', 'while', 'unsupervised', 'learning', 'works', 'with', 'data', 'without', 'predefined', 'labels.']

Sentence 11: Paragraph 11:
Customer segmentation is a business technique used to divide customers into groups
based on shared characteristics or behaviors. Companies may examine purchase
frequency, spending amount, and how recently a customer purchased something.
Words used: ['paragraph', '11:', 'customer', 'segmentation', 'is', 'a', 'business', 'technique', 'used', 'to', 'divide', 'customers', 'into', 'groups', 'based', 'on', 'shared', 'characteristics', 'or', 'behaviors.', 'companies', 'may', 'examine', 'purchase', 'frequency,', 'spending', 'amount,', 'and', 'how', 'recently', 'a', 'customer', 'purchased', 'something.']

Sentence 12: Paragraph 12:
Online shopping has changed the way customers discover and purchase products.
E-commerce businesses collect information about orders, products, prices, customers,
and transaction dates. Analyzing this information can help businesses understand
purchasing patterns.
Words used: ['paragraph', '12:', 'online', 'shopping', 'has', 'changed', 'the', 'way', 'customers', 'discover', 'and', 'purchase', 'products.', 'e-commerce', 'businesses', 'collect', 'information', 'about', 'orders,', 'products,', 'prices,', 'customers,', 'and', 'transaction', 'dates.', 'analyzing', 'this', 'information', 'can', 'help', 'businesses', 'understand', 'purchasing', 'patterns.']

Sentence 13: Paragraph 13:
Artificial intelligence is increasingly used in business applications. Organizations may
use AI to analyze documents, answer customer questions, detect patterns, recommend
products, and automate repetitive tasks.
Words used: ['paragraph', '13:', 'artificial', 'intelligence', 'is', 'increasingly', 'used', 'in', 'business', 'applications.', 'organizations', 'may', 'use', 'ai', 'to', 'analyze', 'documents,', 'answer', 'customer', 'questions,', 'detect', 'patterns,', 'recommend', 'products,', 'and', 'automate', 'repetitive', 'tasks.']

Sentence 14: Paragraph 14:
Natural language processing allows computers to work with human language. Common
NLP tasks include tokenization, stopword removal, stemming, lemmatization, part of
speech tagging, sentiment analysis, and text classification.
Words used: ['paragraph', '14:', 'natural', 'language', 'processing', 'allows', 'computers', 'to', 'work', 'with', 'human', 'language.', 'common', 'nlp', 'tasks', 'include', 'tokenization,', 'stopword', 'removal,', 'stemming,', 'lemmatization,', 'part', 'of', 'speech', 'tagging,', 'sentiment', 'analysis,', 'and', 'text', 'classification.']

Sentence 15: Paragraph 15:
Text similarity is useful when a system needs to determine how closely two pieces of
text are related. Search engines, document retrieval systems, recommendation systems,
and duplicate detection tools can use similarity methods.
Words used: ['paragraph', '15:', 'text', 'similarity', 'is', 'useful', 'when', 'a', 'system', 'needs', 'to', 'determine', 'how', 'closely', 'two', 'pieces', 'of', 'text', 'are', 'related.', 'search', 'engines,', 'document', 'retrieval', 'systems,', 'recommendation', 'systems,', 'and', 'duplicate', 'detection', 'tools', 'can', 'use', 'similarity', 'methods.']

Sentence 16: Paragraph 16:
TF-IDF stands for term frequency inverse document frequency. Term frequency measures
how often a word appears in a document, while inverse document frequency reduces the
importance of words that appear in many documents.
Words used: ['paragraph', '16:', 'tf-idf', 'stands', 'for', 'term', 'frequency', 'inverse', 'document', 'frequency.', 'term', 'frequency', 'measures', 'how', 'often', 'a', 'word', 'appears', 'in', 'a', 'document,', 'while', 'inverse', 'document', 'frequency', 'reduces', 'the', 'importance', 'of', 'words', 'that', 'appear', 'in', 'many', 'documents.']

Sentence 17: Paragraph 17:
Cosine similarity measures the angle between two numerical vectors. A value close to
one generally indicates that the vectors point in similar directions, while a value close
to zero indicates little similarity.
Words used: ['paragraph', '17:', 'cosine', 'similarity', 'measures', 'the', 'angle', 'between', 'two', 'numerical', 'vectors.', 'a', 'value', 'close', 'to', 'one', 'generally', 'indicates', 'that', 'the', 'vectors', 'point', 'in', 'similar', 'directions,', 'while', 'a', 'value', 'close', 'to', 'zero', 'indicates', 'little', 'similarity.']

Sentence 18: Paragraph 18:
Search systems often compare a user's query with a collection of documents. The query
can be converted into the same numerical representation as the documents. A similarity
score can then be calculated for every document.
Words used: ['paragraph', '18:', 'search', 'systems', 'often', 'compare', 'a', "user's", 'query', 'with', 'a', 'collection', 'of', 'documents.', 'the', 'query', 'can', 'be', 'converted', 'into', 'the', 'same', 'numerical', 'representation', 'as', 'the', 'documents.', 'a', 'similarity', 'score', 'can', 'then', 'be', 'calculated', 'for', 'every', 'document.']

Sentence 19: Paragraph 19:
A recommendation system can use similarities between items to suggest content to users.
For example, a system might compare descriptions of books, movies, products, or
articles. Similar descriptions may have higher similarity scores.
Words used: ['paragraph', '19:', 'a', 'recommendation', 'system', 'can', 'use', 'similarities', 'between', 'items', 'to', 'suggest', 'content', 'to', 'users.', 'for', 'example,', 'a', 'system', 'might', 'compare', 'descriptions', 'of', 'books,', 'movies,', 'products,', 'or', 'articles.', 'similar', 'descriptions', 'may', 'have', 'higher', 'similarity', 'scores.']

Sentence 20: Paragraph 20:
Data visualization helps people understand information through charts and graphs.
Bar charts can compare categories, line charts can show changes over time, histograms
can display distributions, and scatter plots can show relationships between variables.
Words used: ['paragraph', '20:', 'data', 'visualization', 'helps', 'people', 'understand', 'information', 'through', 'charts', 'and', 'graphs.', 'bar', 'charts', 'can', 'compare', 'categories,', 'line', 'charts', 'can', 'show', 'changes', 'over', 'time,', 'histograms', 'can', 'display', 'distributions,', 'and', 'scatter', 'plots', 'can', 'show', 'relationships', 'between', 'variables.']

Sentence 21: Paragraph 21:
A database stores organized information so that it can be searched, updated, and
managed efficiently. Relational databases commonly organize information into tables
containing rows and columns. SQL can be used to select, filter, group, and sort data.
Words used: ['paragraph', '21:', 'a', 'database', 'stores', 'organized', 'information', 'so', 'that', 'it', 'can', 'be', 'searched,', 'updated,', 'and', 'managed', 'efficiently.', 'relational', 'databases', 'commonly', 'organize', 'information', 'into', 'tables', 'containing', 'rows', 'and', 'columns.', 'sql', 'can', 'be', 'used', 'to', 'select,', 'filter,', 'group,', 'and', 'sort', 'data.']

Sentence 22: Paragraph 22:
Cybersecurity focuses on protecting computers, networks, applications, and information
from unauthorized access or damage. Strong passwords, multi-factor authentication,

In [5]:
tfidf_matrix = vectorizer.fit_transform(sentences + query)

sentence_vectors = tfidf_matrix[:-1]
query_vector = tfidf_matrix[-1]

tfidf_df = pd.DataFrame(
    sentence_vectors.toarray(),
    columns=vocab,
    index=sentences
)

sentence_bow = []

for sentence in sentences:
    row = tfidf_df.loc[sentence]
    bow = row[row > 0]

    sentence_bow.append({
        "Sentence": sentence,
        "Bag_of_TFIDF_Vectors": bow.to_dict()
    })


query_row = pd.Series(
    query_vector.toarray()[0],
    index=vocab
)

query_bow = query_row[query_row > 0]

sentence_bow.append({

    "Bag_of_TFIDF_Vectors": query_bow.to_dict()
})

final_df = pd.DataFrame(sentence_bow)

final_df.style.set_properties(
    **{
        'text-align': 'left',
        'font-family': 'monospace',
        'white-space': 'pre',
    }
)

In [6]:
import numpy as np

query_array = query_vector.toarray()[0]

for i in range(len(sentences)):
    sentence_array = sentence_vectors[i].toarray()[0]
    dot = np.dot(query_array, sentence_array)
    print(f"Dot product with sentence {i+1}: {dot}")

Dot product with sentence 1: 0.09024769825207814
Dot product with sentence 2: 0.0
Dot product with sentence 3: 0.0
Dot product with sentence 4: 0.0
Dot product with sentence 5: 0.05973676517796999
Dot product with sentence 6: 0.0
Dot product with sentence 7: 0.0
Dot product with sentence 8: 0.10471152184410427
Dot product with sentence 9: 0.0
Dot product with sentence 10: 0.05673541715595476
Dot product with sentence 11: 0.0
Dot product with sentence 12: 0.0
Dot product with sentence 13: 0.0
Dot product with sentence 14: 0.06327310454528741
Dot product with sentence 15: 0.0
Dot product with sentence 16: 0.0
Dot product with sentence 17: 0.0
Dot product with sentence 18: 0.058935479576771234
Dot product with sentence 19: 0.0
Dot product with sentence 20: 0.08175472376614815
Dot product with sentence 21: 0.0
Dot product with sentence 22: 0.0
Dot product with sentence 23: 0.0
Dot product with sentence 24: 0.0
Dot product with sentence 25: 0.0
Dot product with sentence 26: 0.0
Dot product with sentence 27: 0.06400357797166335
Dot product with sentence 28: 0.0
Dot product with sentence 29: 0.0
Dot product with sentence 30: 0.0
Dot product with sentence 31: 0.0
Dot product with sentence 32: 0.0
Dot product with sentence 33: 0.0
Dot product with sentence 34: 0.0678181835508501
Dot product with sentence 35: 0.28124576768221204
Dot product with sentence 36: 0.0
Dot product with sentence 37: 0.0
Dot product with sentence 38: 0.0
Dot product with sentence 39: 0.0
Dot product with sentence 40: 0.0

In [7]:
query_mag = np.sqrt(np.sum(query_array ** 2))
print("Query magnitude:", query_mag)

for i in range(len(sentences)):
    sentence_array = sentence_vectors[i].toarray()[0]
    sent_mag = np.sqrt(np.sum(sentence_array ** 2))
    print(f"Magnitude of sentence {i+1}:", sent_mag)

Query magnitude: 1.0
Magnitude of sentence 1: 1.0
Magnitude of sentence 2: 1.0
Magnitude of sentence 3: 0.9999999999999999
Magnitude of sentence 4: 0.9999999999999999
Magnitude of sentence 5: 1.0000000000000002
Magnitude of sentence 6: 1.0
Magnitude of sentence 7: 0.9999999999999998
Magnitude of sentence 8: 0.9999999999999999
Magnitude of sentence 9: 1.0
Magnitude of sentence 10: 1.0
Magnitude of sentence 11: 1.0
Magnitude of sentence 12: 1.0
Magnitude of sentence 13: 1.0
Magnitude of sentence 14: 1.0000000000000002
Magnitude of sentence 15: 0.9999999999999999
Magnitude of sentence 16: 1.0
Magnitude of sentence 17: 0.9999999999999999
Magnitude of sentence 18: 1.0
Magnitude of sentence 19: 1.0
Magnitude of sentence 20: 1.0
Magnitude of sentence 21: 1.0
Magnitude of sentence 22: 1.0
Magnitude of sentence 23: 0.9999999999999999
Magnitude of sentence 24: 1.0
Magnitude of sentence 25: 1.0
Magnitude of sentence 26: 1.0
Magnitude of sentence 27: 1.0
Magnitude of sentence 28: 1.0
Magnitude of sentence 29: 0.9999999999999999
Magnitude of sentence 30: 1.0
Magnitude of sentence 31: 1.0000000000000002
Magnitude of sentence 32: 1.0000000000000002
Magnitude of sentence 33: 1.0
Magnitude of sentence 34: 1.0
Magnitude of sentence 35: 1.0000000000000002
Magnitude of sentence 36: 1.0000000000000002
Magnitude of sentence 37: 1.0
Magnitude of sentence 38: 1.0000000000000002
Magnitude of sentence 39: 0.9999999999999999
Magnitude of sentence 40: 0.9999999999999999

In [8]:
results = []
for i in range(len(sentences)):
    sentence_array = sentence_vectors[i].toarray()[0]

    dot = np.dot(query_array, sentence_array)
    sent_mag = np.sqrt(np.sum(sentence_array ** 2))

    cosine_sim = dot / (query_mag * sent_mag)

    print(f"\nSentence: {sentences[i]}")
    print("Cosine Similarity:", cosine_sim)

    results.append({
        "Sentence": sentences[i],
        "Cosine Similarity": cosine_sim
    })

    print(f"\nSentence {i+1}: {sentences[i]}")
    print("Cosine Similarity:", cosine_sim)

Sentence: Paragraph 1:
Workplace stress can affect employees in many different ways. Long working hours,
heavy workloads, strict deadlines, and pressure from managers can make people feel
tired and overwhelmed. When stress continues for a long period, employees may have
difficulty concentrating and may become less productive.
Cosine Similarity: 0.09024769825207814

Sentence 1: Paragraph 1:
Workplace stress can affect employees in many different ways. Long working hours,
heavy workloads, strict deadlines, and pressure from managers can make people feel
tired and overwhelmed. When stress continues for a long period, employees may have
difficulty concentrating and may become less productive.
Cosine Similarity: 0.09024769825207814

Sentence: Paragraph 2:
Maintaining a healthy work life balance is important for physical and mental well-being.
Employees need enough time for work, family, friends, exercise, hobbies, and rest.
When work takes up nearly all of a person's time, stress and dissatisfaction can increase.
Cosine Similarity: 0.0

Sentence 2: Paragraph 2:
Maintaining a healthy work life balance is important for physical and mental well-being.
Employees need enough time for work, family, friends, exercise, hobbies, and rest.
When work takes up nearly all of a person's time, stress and dissatisfaction can increase.
Cosine Similarity: 0.0

Sentence: Paragraph 3:
Exercise is one way people can improve their physical health and manage everyday stress.
Walking, running, swimming, cycling, and strength training can help people stay active.
Regular physical activity may also improve sleep and mood.
Cosine Similarity: 0.0

Sentence 3: Paragraph 3:
Exercise is one way people can improve their physical health and manage everyday stress.
Walking, running, swimming, cycling, and strength training can help people stay active.
Regular physical activity may also improve sleep and mood.
Cosine Similarity: 0.0

Sentence: Paragraph 4:
Good sleep is an important part of a healthy lifestyle. Adults need consistent quality
sleep to support concentration, memory, mood, and physical health. Staying up late to
finish work can make people tired the next day.
Cosine Similarity: 0.0

Sentence 4: Paragraph 4:
Good sleep is an important part of a healthy lifestyle. Adults need consistent quality
sleep to support concentration, memory, mood, and physical health. Staying up late to
finish work can make people tired the next day.
Cosine Similarity: 0.0

Sentence: Paragraph 5:
Healthy eating provides the body with nutrients and energy needed for daily activities.
A balanced diet can include vegetables, fruits, whole grains, protein sources, and
healthy fats. Drinking enough water is also important.
Cosine Similarity: 0.059736765177969976

Sentence 5: Paragraph 5:
Healthy eating provides the body with nutrients and energy needed for daily activities.
A balanced diet can include vegetables, fruits, whole grains, protein sources, and
healthy fats. Drinking enough water is also important.
Cosine Similarity: 0.059736765177969976

Sentence: Paragraph 6:
Time management can help students and employees complete their responsibilities
without unnecessary pressure. A person can make a list of important tasks, organize
them by priority, and divide large projects into smaller steps.
Cosine Similarity: 0.0

Sentence 6: Paragraph 6:
Time management can help students and employees complete their responsibilities
without unnecessary pressure. A person can make a list of important tasks, organize
them by priority, and divide large projects into smaller steps.
Cosine Similarity: 0.0

Sentence: Paragraph 7:
Learning new skills requires practice, patience, and repetition. Beginners often make
mistakes when they first learn programming, mathematics, writing, or another subject.
Mistakes can provide useful information about what needs more practice.
Cosine Similarity: 0.0

Sentence 7: Paragraph 7:
Learning new skills requires practice, patience, and repetition. Beginners often make
mistakes when they first learn programming, mathematics, writing, or another subject.
Mistakes can provide useful information about what needs more practice.
Cosine Similarity: 0.0

Sentence: Paragraph 8:
Python is a popular programming language used for data analysis, automation, web
development, and machine learning. Beginners often start by learning variables,
strings, numbers, lists, dictionaries, conditions, and loops.
Cosine Similarity: 0.10471152184410429

Sentence 8: Paragraph 8:
Python is a popular programming language used for data analysis, automation, web
development, and machine learning. Beginners often start by learning variables,
strings, numbers, lists, dictionaries, conditions, and loops.
Cosine Similarity: 0.10471152184410429

Sentence: Paragraph 9:
Data analysis involves collecting, cleaning, exploring, and interpreting information.
A data analyst may begin by loading a dataset and checking its rows, columns, data
types, and missing values. After cleaning the data, the analyst can calculate statistics.
Cosine Similarity: 0.0

Sentence 9: Paragraph 9:
Data analysis involves collecting, cleaning, exploring, and interpreting information.
A data analyst may begin by loading a dataset and checking its rows, columns, data
types, and missing values. After cleaning the data, the analyst can calculate statistics.
Cosine Similarity: 0.0

Sentence: Paragraph 10:
Machine learning allows computers to learn patterns from data and use those patterns
to make predictions or classifications. Supervised learning uses labeled data, while
unsupervised learning works with data without predefined labels.
Cosine Similarity: 0.05673541715595476

Sentence 10: Paragraph 10:
Machine learning allows computers to learn patterns from data and use those patterns
to make predictions or classifications. Supervised learning uses labeled data, while
unsupervised learning works with data without predefined labels.
Cosine Similarity: 0.05673541715595476

Sentence: Paragraph 11:
Customer segmentation is a business technique used to divide customers into groups
based on shared characteristics or behaviors. Companies may examine purchase
frequency, spending amount, and how recently a customer purchased something.
Cosine Similarity: 0.0

Sentence 11: Paragraph 11:
Customer segmentation is a business technique used to divide customers into groups
based on shared characteristics or behaviors. Companies may examine purchase
frequency, spending amount, and how recently a customer purchased something.
Cosine Similarity: 0.0

Sentence: Paragraph 12:
Online shopping has changed the way customers discover and purchase products.
E-commerce businesses collect information about orders, products, prices, customers,
and transaction dates. Analyzing this information can help businesses understand
purchasing patterns.
Cosine Similarity: 0.0

Sentence 12: Paragraph 12:
Online shopping has changed the way customers discover and purchase products.
E-commerce businesses collect information about orders, products, prices, customers,
and transaction dates. Analyzing this information can help businesses understand
purchasing patterns.
Cosine Similarity: 0.0

Sentence: Paragraph 13:
Artificial intelligence is increasingly used in business applications. Organizations may
use AI to analyze documents, answer customer questions, detect patterns, recommend
products, and automate repetitive tasks.
Cosine Similarity: 0.0

Sentence 13: Paragraph 13:
Artificial intelligence is increasingly used in business applications. Organizations may
use AI to analyze documents, answer customer questions, detect patterns, recommend
products, and automate repetitive tasks.
Cosine Similarity: 0.0

Sentence: Paragraph 14:
Natural language processing allows computers to work with human language. Common
NLP tasks include tokenization, stopword removal, stemming, lemmatization, part of
speech tagging, sentiment analysis, and text classification.
Cosine Similarity: 0.0632731045452874

Sentence 14: Paragraph 14:
Natural language processing allows computers to work with human language. Common
NLP tasks include tokenization, stopword removal, stemming, lemmatization, part of
speech tagging, sentiment analysis, and text classification.
Cosine Similarity: 0.0632731045452874

Sentence: Paragraph 15:
Text similarity is useful when a system needs to determine how closely two pieces of
text are related. Search engines, document retrieval systems, recommendation systems,
and duplicate detection tools can use similarity methods.
Cosine Similarity: 0.0

Sentence 15: Paragraph 15:
Text similarity is useful when a system needs to determine how closely two pieces of
text are related. Search engines, document retrieval systems, recommendation systems,
and duplicate detection tools can use similarity methods.
Cosine Similarity: 0.0

Sentence: Paragraph 16:
TF-IDF stands for term frequency inverse document frequency. Term frequency measures
how often a word appears in a document, while inverse document frequency reduces the
importance of words that appear in many documents.
Cosine Similarity: 0.0

Sentence 16: Paragraph 16:
TF-IDF stands for term frequency inverse document frequency. Term frequency measures
how often a word appears in a document, while inverse document frequency reduces the
importance of words that appear in many documents.
Cosine Similarity: 0.0

Sentence: Paragraph 17:
Cosine similarity measures the angle between two numerical vectors. A value close to
one generally indicates that the vectors point in similar directions, while a value close
to zero indicates little similarity.
Cosine Similarity: 0.0

Sentence 17: Paragraph 17:
Cosine similarity measures the angle between two numerical vectors. A value close to
one generally indicates that the vectors point in similar directions, while a value close
to zero indicates little similarity.
Cosine Similarity: 0.0

Sentence: Paragraph 18:
Search systems often compare a user's query with a collection of documents. The query
can be converted into the same numerical representation as the documents. A similarity
score can then be calculated for every document.
Cosine Similarity: 0.058935479576771234

Sentence 18: Paragraph 18:
Search systems often compare a user's query with a collection of documents. The query
can be converted into the same numerical representation as the documents. A similarity
score can then be calculated for every document.
Cosine Similarity: 0.058935479576771234

Sentence: Paragraph 19:
A recommendation system can use similarities between items to suggest content to users.
For example, a system might compare descriptions of books, movies, products, or
articles. Similar descriptions may have higher similarity scores.
Cosine Similarity: 0.0

Sentence 19: Paragraph 19:
A recommendation system can use similarities between items to suggest content to users.
For example, a system might compare descriptions of books, movies, products, or
articles. Similar descriptions may have higher similarity scores.
Cosine Similarity: 0.0

Sentence: Paragraph 20:
Data visualization helps people understand information through charts and graphs.
Bar charts can compare categories, line charts can show changes over time, histograms
can display distributions, and scatter plots can show relationships between variables.
Cosine Similarity: 0.08175472376614815

Sentence 20: Paragraph 20:
Data visualization helps people understand information through charts and graphs.
Bar charts can compare categories, line charts can show changes over time, histograms
can display distributions, and scatter plots can show relationships between variables.
Cosine Similarity: 0.08175472376614815

Sentence: Paragraph 21:
A database stores organized information so that it can be searched, updated, and
managed efficiently. Relational databases commonly organize information into tables
containing rows and columns. SQL can be used to select, filter, group, and sort data.
Cosine Similarity: 0.0

Sentence 21: Paragraph 21:
A database stores organized information so that it can be searched, updated, and
managed efficiently. Relational databases commonly organize information into tables
containing rows and columns. SQL can be used to select, filter, group, and sort data.
Cosine Similarity: 0.0

Sentence: Paragraph 22:
Cybersecurity focuses on protecting computers, networks, applications, and information
from unauthorized access or damage. Strong passwords, multi-factor authentication,
software updates, and backups can reduce security risks.
Cosine Similarity: 0.0

Sentence 22: Paragraph 22:
Cybersecurity focuses on protecting computers, networks, applications, and information
from unauthorized access or damage. Strong passwords, multi-factor authentication,
software updates, and backups can reduce security risks.
Cosine Similarity: 0.0

Sentence: Paragraph 23:
Cloud computing provides access to computing resources such as storage, databases,
servers, and applications through internet-connected services. Businesses can use cloud
platforms to store data and run applications.
Cosine Similarity: 0.0

Sentence 23: Paragraph 23:
Cloud computing provides access to computing resources such as storage, databases,
servers, and applications through internet-connected services. Businesses can use cloud
platforms to store data and run applications.
Cosine Similarity: 0.0

Sentence: Paragraph 24:
Project management involves planning work, assigning responsibilities, tracking progress,
and managing deadlines. A project may be divided into smaller tasks so that progress
can be measured.
Cosine Similarity: 0.0

Sentence 24: Paragraph 24:
Project management involves planning work, assigning responsibilities, tracking progress,
and managing deadlines. A project may be divided into smaller tasks so that progress
can be measured.
Cosine Similarity: 0.0

Sentence: Paragraph 25:
Communication is an important skill in education and the workplace. Clear communication
helps people understand expectations, explain ideas, and solve problems. Asking
questions and listening carefully can reduce misunderstandings.
Cosine Similarity: 0.0

Sentence 25: Paragraph 25:
Communication is an important skill in education and the workplace. Clear communication
helps people understand expectations, explain ideas, and solve problems. Asking
questions and listening carefully can reduce misunderstandings.
Cosine Similarity: 0.0

Sentence: Paragraph 26:
Financial planning helps people understand their income, expenses, savings, and financial
goals. Creating a budget can show where money is being spent each month. People may
set aside money for emergencies, education, housing, or retirement.
Cosine Similarity: 0.0

Sentence 26: Paragraph 26:
Financial planning helps people understand their income, expenses, savings, and financial
goals. Creating a budget can show where money is being spent each month. People may
set aside money for emergencies, education, housing, or retirement.
Cosine Similarity: 0.0

Sentence: Paragraph 27:
Investing involves putting money into assets with the expectation that they may generate
returns over time. Stocks, bonds, mutual funds, and other investments have different
characteristics and levels of risk.
Cosine Similarity: 0.06400357797166335

Sentence 27: Paragraph 27:
Investing involves putting money into assets with the expectation that they may generate
returns over time. Stocks, bonds, mutual funds, and other investments have different
characteristics and levels of risk.
Cosine Similarity: 0.06400357797166335

Sentence: Paragraph 28:
Weather describes atmospheric conditions such as temperature, precipitation, wind,
humidity, and cloud cover. Weather can change from day to day and sometimes from
hour to hour.
Cosine Similarity: 0.0

Sentence 28: Paragraph 28:
Weather describes atmospheric conditions such as temperature, precipitation, wind,
humidity, and cloud cover. Weather can change from day to day and sometimes from
hour to hour.
Cosine Similarity: 0.0

Sentence: Paragraph 29:
Climate change refers to long-term changes in temperatures and weather patterns.
Scientists study temperature records, ocean measurements, ice observations, and other
evidence to understand climate trends.
Cosine Similarity: 0.0

Sentence 29: Paragraph 29:
Climate change refers to long-term changes in temperatures and weather patterns.
Scientists study temperature records, ocean measurements, ice observations, and other
evidence to understand climate trends.
Cosine Similarity: 0.0

Sentence: Paragraph 30:
Travel planning involves choosing destinations, transportation, accommodation, activities,
and a budget. Travelers may research weather, local transportation, cultural attractions,
and seasonal conditions before a trip.
Cosine Similarity: 0.0

Sentence 30: Paragraph 30:
Travel planning involves choosing destinations, transportation, accommodation, activities,
and a budget. Travelers may research weather, local transportation, cultural attractions,
and seasonal conditions before a trip.
Cosine Similarity: 0.0

Sentence: Paragraph 31:
Reading is an effective way to develop knowledge and language skills. Regular reading
exposes people to new vocabulary, ideas, writing styles, and information. Students can
improve comprehension by identifying the main idea and supporting details.
Cosine Similarity: 0.0

Sentence 31: Paragraph 31:
Reading is an effective way to develop knowledge and language skills. Regular reading
exposes people to new vocabulary, ideas, writing styles, and information. Students can
improve comprehension by identifying the main idea and supporting details.
Cosine Similarity: 0.0

Sentence: Paragraph 32:
Writing requires organizing ideas so that readers can follow the information easily.
A strong paragraph usually has a clear main idea followed by supporting information.
Revising a draft can improve grammar, structure, word choice, and clarity.
Cosine Similarity: 0.0

Sentence 32: Paragraph 32:
Writing requires organizing ideas so that readers can follow the information easily.
A strong paragraph usually has a clear main idea followed by supporting information.
Revising a draft can improve grammar, structure, word choice, and clarity.
Cosine Similarity: 0.0

Sentence: Paragraph 33:
A large document may contain hundreds or thousands of paragraphs covering different
topics. Finding relevant information manually can take a long time. Text similarity
methods can help a program identify paragraphs that are related to a search query.
Cosine Similarity: 0.0

Sentence 33: Paragraph 33:
A large document may contain hundreds or thousands of paragraphs covering different
topics. Finding relevant information manually can take a long time. Text similarity
methods can help a program identify paragraphs that are related to a search query.
Cosine Similarity: 0.0

Sentence: Paragraph 34:
Employees may experience pressure when they have too many tasks and not enough
time to complete them. Planning work carefully and communicating with managers can
help teams understand priorities and deadlines.
Cosine Similarity: 0.0678181835508501

Sentence 34: Paragraph 34:
Employees may experience pressure when they have too many tasks and not enough
time to complete them. Planning work carefully and communicating with managers can
help teams understand priorities and deadlines.
Cosine Similarity: 0.0678181835508501

Sentence: Paragraph 35:
Students can improve their programming skills by practicing small Python programs.
Working with variables, loops, conditions, functions, lists, and dictionaries creates a
foundation for more advanced data science and machine learning.
Cosine Similarity: 0.281245767682212

Sentence 35: Paragraph 35:
Students can improve their programming skills by practicing small Python programs.
Working with variables, loops, conditions, functions, lists, and dictionaries creates a
foundation for more advanced data science and machine learning.
Cosine Similarity: 0.281245767682212


In [9]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Cosine Similarity",
    ascending=False
)

results_df = results_df.reset_index(drop=True)

print("\nSimilarity Results:")
display(results_df)
# ==========================================
# Find the most similar paragraph
# ==========================================

most_similar = results_df.iloc[0]

print("\n" + "=" * 70)

print("MOST SIMILAR RESULT")

print("=" * 70)

print("\nParagraph:")
print(most_similar["Sentence"])

print("\nCosine Similarity:")
print(most_similar["Cosine Similarity"])

print("\nThis paragraph is more similar to your query.")

Similarity Results:

                                             Sentence  Cosine Similarity
0   Paragraph 35:\nStudents can improve their prog...           0.281246
1   Paragraph 8:\nPython is a popular programming ...           0.104712
2   Paragraph 1:\nWorkplace stress can affect empl...           0.090248
3   Paragraph 20:\nData visualization helps people...           0.081755
4   Paragraph 34:\nEmployees may experience pressu...           0.067818
5   Paragraph 27:\nInvesting involves putting mone...           0.064004
6   Paragraph 14:\nNatural language processing all...           0.063273
7   Paragraph 5:\nHealthy eating provides the body...           0.059737
8   Paragraph 18:\nSearch systems often compare a ...           0.058935
9   Paragraph 10:\nMachine learning allows compute...           0.056735
10  Paragraph 7:\nLearning new skills requires pra...           0.000000
11  Paragraph 4:\nGood sleep is an important part ...           0.000000
12  Paragraph 2:\nMaintaining a healthy work life ...           0.000000
13  Paragraph 6:\nTime management can help student...           0.000000
14  Paragraph 3:\nExercise is one way people can i...           0.000000
15  Paragraph 12:\nOnline shopping has changed the...           0.000000
16  Paragraph 16:\nTF-IDF stands for term frequenc...           0.000000
17  Paragraph 15:\nText similarity is useful when ...           0.000000
18  Paragraph 17:\nCosine similarity measures the ...           0.000000
19  Paragraph 19:\nA recommendation system can use...           0.000000
20  Paragraph 21:\nA database stores organized inf...           0.000000
21  Paragraph 13:\nArtificial intelligence is incr...           0.000000
22  Paragraph 11:\nCustomer segmentation is a busi...           0.000000
23  Paragraph 9:\nData analysis involves collectin...           0.000000
24  Paragraph 24:\nProject management involves pla...           0.000000
25  Paragraph 23:\nCloud computing provides access...           0.000000
26  Paragraph 22:\nCybersecurity focuses on protec...           0.000000
27  Paragraph 25:\nCommunication is an important s...           0.000000
28  Paragraph 29:\nClimate change refers to long-t...           0.000000
29  Paragraph 30:\nTravel planning involves choosi...           0.000000
30  Paragraph 26:\nFinancial planning helps people...           0.000000
31  Paragraph 28:\nWeather describes atmospheric c...           0.000000
32  Paragraph 32:\nWriting requires organizing ide...           0.000000
33  Paragraph 31:\nReading is an effective way to ...           0.000000
34  Paragraph 33:\nA large document may contain hu...           0.000000
35  Paragraph 36:\nA data scientist may use pandas...           0.000000
36  Paragraph 37:\nMachine learning models should ...           0.000000
37  Paragraph 38:\nNatural language processing can...           0.000000
38  Paragraph 39:\nDocument similarity can help us...           0.000000
39  Paragraph 40:\nThe purpose of a text search sy...           0.000000

======================================================================
MOST SIMILAR RESULT
======================================================================

Paragraph:
Paragraph 35:
Students can improve their programming skills by practicing small Python programs.
Working with variables, loops, conditions, functions, lists, and dictionaries creates a
foundation for more advanced data science and machine learning.

Cosine Similarity:
0.281245767682212

This paragraph is more similar to your query.