In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
sentences=['The young student is reading a Python book in the classroom',
'The young student is writing Python code on the computer',
'The teacher is reading the Python book while the students are writing notes',]
#'The students are learning Python in the classroom with their teacher']

In [25]:
vectors=TfidfVectorizer()
vectors.fit(sentences)

transform=vectors.transform(sentences)
print(transform)
print(vectors.vocabulary_)
print(transform.shape)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 29 stored elements and shape (3, 18)>
  Coords	Values
  (0, 1)	0.30047020670788505
  (0, 2)	0.39508221339221145
  (0, 5)	0.39508221339221145
  (0, 6)	0.23334191966793622
  (0, 9)	0.23334191966793622
  (0, 10)	0.30047020670788505
  (0, 11)	0.30047020670788505
  (0, 14)	0.46668383933587243
  (0, 17)	0.30047020670788505
  (1, 3)	0.38269084223774363
  (1, 4)	0.38269084223774363
  (1, 6)	0.22602337624965532
  (1, 8)	0.38269084223774363
  (1, 9)	0.22602337624965532
  (1, 11)	0.29104624955170477
  (1, 14)	0.45204675249931064
  (1, 16)	0.29104624955170477
  (1, 17)	0.29104624955170477
  (2, 0)	0.30754967211277107
  (2, 1)	0.2338994528739479
  (2, 6)	0.18164379071349276
  (2, 7)	0.30754967211277107
  (2, 9)	0.18164379071349276
  (2, 10)	0.2338994528739479
  (2, 12)	0.30754967211277107
  (2, 13)	0.30754967211277107
  (2, 14)	0.5449313721404783
  (2, 15)	0.30754967211277107
  (2, 16)	0.2338994528739479
{'the': 14, 'young': 17, 'student': 11, 'is': 6, 'reading': 10, 'python': 9, 'book': 1, 'in': 5, 'classroom': 2, 'writing': 16, 'code': 3, 'on': 8, 'computer': 4, 'teacher': 13, 'while': 15, 'students': 12, 'are': 0, 'notes': 7}
(3, 18)

In [26]:
#binary
vectors=TfidfVectorizer(use_idf=True)
vectors.fit(sentences)
transform=vectors.transform(sentences)
print(transform)
print(transform.toarray())
sentences=['The young student is reading a Python book in the classroom',
'The young student is writing Python code on the computer',
'The teacher is reading the Python book while the students are writing notes',
'The students are learning Python in the classroom with their teacher']

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 29 stored elements and shape (3, 18)>
  Coords	Values
  (0, 1)	0.30047020670788505
  (0, 2)	0.39508221339221145
  (0, 5)	0.39508221339221145
  (0, 6)	0.23334191966793622
  (0, 9)	0.23334191966793622
  (0, 10)	0.30047020670788505
  (0, 11)	0.30047020670788505
  (0, 14)	0.46668383933587243
  (0, 17)	0.30047020670788505
  (1, 3)	0.38269084223774363
  (1, 4)	0.38269084223774363
  (1, 6)	0.22602337624965532
  (1, 8)	0.38269084223774363
  (1, 9)	0.22602337624965532
  (1, 11)	0.29104624955170477
  (1, 14)	0.45204675249931064
  (1, 16)	0.29104624955170477
  (1, 17)	0.29104624955170477
  (2, 0)	0.30754967211277107
  (2, 1)	0.2338994528739479
  (2, 6)	0.18164379071349276
  (2, 7)	0.30754967211277107
  (2, 9)	0.18164379071349276
  (2, 10)	0.2338994528739479
  (2, 12)	0.30754967211277107
  (2, 13)	0.30754967211277107
  (2, 14)	0.5449313721404783
  (2, 15)	0.30754967211277107
  (2, 16)	0.2338994528739479
[[0.         0.30047021 0.39508221 0.         0.         0.39508221
  0.23334192 0.         0.         0.23334192 0.30047021 0.30047021
  0.         0.         0.46668384 0.         0.         0.30047021]
 [0.         0.         0.         0.38269084 0.38269084 0.
  0.22602338 0.         0.38269084 0.22602338 0.         0.29104625
  0.         0.         0.45204675 0.         0.29104625 0.29104625]
 [0.30754967 0.23389945 0.         0.         0.         0.
  0.18164379 0.30754967 0.         0.18164379 0.23389945 0.
  0.30754967 0.30754967 0.54493137 0.30754967 0.23389945 0.        ]]

In [28]:
import pandas as pd
df=pd.DataFrame(vectors.fit_transform(sentences).toarray(), columns=vectors.get_feature_names_out())

sentences=['The young student is reading a Python book in the classroom',
'The young student is writing Python code on the computer',
'The teacher is reading the Python book while the students are writing notes',]
#'The students are learning Python in the classroom with their teacher']
df

,are,book,classroom,code,computer,in,is,notes,on,python,reading,student,students,teacher,the,while,writing,young
0,0.00000,0.300470,0.395082,0.000000,0.000000,0.395082,0.233342,0.00000,0.000000,0.233342,0.300470,0.300470,0.00000,0.00000,0.466684,0.00000,0.000000,0.300470
1,0.00000,0.000000,0.000000,0.382691,0.382691,0.000000,0.226023,0.00000,0.382691,0.226023,0.000000,0.291046,0.00000,0.00000,0.452047,0.00000,0.291046,0.291046
2,0.30755,0.233899,0.000000,0.000000,0.000000,0.000000,0.181644,0.30755,0.000000,0.181644,0.233899,0.000000,0.30755,0.30755,0.544931,0.30755,0.233899,0.000000

In [29]:
df['python']

0    0.233342
1    0.226023
2    0.181644
Name: python, dtype: float64